workflows:
  my-workflow:
    name: driver build
    labels:
      - test
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: test
        script: echo 'test comp'
    # artifacts:
    #   - build/**/outputs/repo
    #   - build/ios/framework
    publishing:
      email:
        recipients:
          - shinnaga.dev@gmail.com
      scripts:
        - echo 'Post-publish script'